import { Barlow } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";

const barlow = Barlow({ subsets: ["latin"],  weight: ["500"]});

export const metadata = {
  title: "Sistema Familiograma",
  description: "Generated by create next app",
  manifest: "/manifest.json",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{ margin: 0 }} className={barlow.className}>
        {children}
      </body>
    </html>
  );
}
